'epoch': 100
'batch_size': 600
'input_size': 28
'z_dim': 100
'supervised': False
'len_discrete_code': 10
'len_continuous_code': 2
'lrG': 0.001
'lrD': 0.0002
'lambda': 1.0
'beta1': 0.5
'beta2': 0.999
'report_interval_iter': 50
'sample_per_code': 10
'save_fig_interval_iter': 1000
'snapshot_interval_epoch': 20
'dataset_name': mnist
'data_root_dir': ./